site_name: "Question Space System (QSS)"
site_description: ""
site_author: "Viktor Jevdokimov, Vilnius, Lithuania"
copyright: "Â© 2025 3in3.dev"

docs_dir: src

theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.sections
    - navigation.expand
    - navigation.footer
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tracking
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

plugins:
  - search
  - to-pdf:
      output_path: "pdf/qss.pdf"
      cover_subtitle: ""
      toc_level: 3
      ordered_chapter_level: 3

nav:
  - INTRODUCTION & QUICK START:
    - index.md
    - 000-intro/010-how-to-use-this-system.md
  - THEORY:
    - 100-theory/100-vision-principles-beliefs.md
    - 100-theory/110-what-is-a-question-space.md
    - 100-theory/120-core-architecture-orientation-topology-flow-recursion.md
    - 100-theory/130-dimensions-of-inquiry.md
    - 100-theory/140-modes-and-lifecycle.md
    - 100-theory/150-patterns-and-anti-patterns.md
  - PRACTICE:
    - 200-practice/200-practical-overview.md
    - 200-practice/210-quickstart-builder.md
    - 200-practice/220-context-intake-and-orientation.md
    - 200-practice/230-designing-the-topology-dimensions.md
    - 200-practice/240-designing-flow-and-pathways.md
    - 200-practice/250-recursion-and-iteration-loops.md
    - 200-practice/260-domain-playbooks-software-delivery-consulting.md
    - 200-practice/261-domain-playbook-personal-reflection.md
    - 200-practice/262-domain-playbook-music-production.md
  - REFERENCE:
    - 300-reference/300-glossary.md
    - 300-reference/310-question-pattern-cheatsheets.md
    - 300-reference/320-templates-and-checklists.md
    - 300-reference/330-example-question-spaces-case-studies.md
#    - 300-reference/390-version-and-licensing.md
#    - author.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
